# Generated by Django 2.1.7 on 2019-02-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_active',
            new_name='isactive',
        ),
    ]
