# Generated by Django 2.1.7 on 2019-02-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='haze',
            options={'verbose_name_plural': 'Haze Objects'},
        ),
    ]
