# Generated by Django 2.1.7 on 2019-02-17 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20190216_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crisistransactionlog',
            options={'verbose_name': 'Event Transaction Log', 'verbose_name_plural': 'Event Transaction Logs'},
        ),
        migrations.AlterModelOptions(
            name='eventtransactionlog',
            options={'verbose_name': 'Event Transaction Log', 'verbose_name_plural': 'Event Transaction Logs'},
        ),
    ]
