# Generated by Django 2.1.7 on 2019-02-17 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20190217_0210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crisistransactionlog',
            options={'verbose_name': 'Crisis Transaction Log', 'verbose_name_plural': 'Crisis Transaction Logs'},
        ),
    ]
