# Generated by Django 2.1.7 on 2019-02-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20190217_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='condition',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
