# Generated by Django 2.1.7 on 2019-02-17 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_auto_20190217_0351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='haze',
            old_name='district_name',
            new_name='region_name',
        ),
    ]
